version: '3.6'
services:
  postgres:
    container_name: postgres
    image: postgres:12
    ports:
    - "5432:5432"
    restart: always
    volumes:
    - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

