version: '3.6'
services:
  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    networks:
      - application_prod_network
    ports:
    - "5432:5432"
    volumes:
    - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  postgres_airflow:
    container_name: postgres_airflow
    image: postgres:12
    restart: always
    networks:
      - application_prod_network
    volumes:
    - ./data/postgres-airflow:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_AIRFLOW_DB}
      POSTGRES_USER: ${POSTGRES_AIRFLOW_USER}
      POSTGRES_PASSWORD: ${POSTGRES_AIRFLOW_PASSWORD}

networks:
  application_prod_network:
    driver: bridge
    name: application_prod_network

