version: '3.6'
services:
  hasura:
      image: hasura/graphql-engine:v2.0.0-alpha.4
      container_name: hasura
      networks:
        - application_prod_network
      ports:
        - "8080:8080"
      depends_on:
        - "postgres"
      restart: always
      environment:
        HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
        ## enable the console served by server
        HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
        ## enable debugging mode. It is recommended to disable this in production
        HASURA_GRAPHQL_DEV_MODE: "true"
        HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
        ## uncomment next line to set an admin secret
        HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}

networks:
  application_prod_network:
    driver: bridge
    name: application_prod_network

