name: Deploy Hasura

on:
  push:
    paths:
      - "hasura/**"
      - ".github/workflows/hasura.yml"
    branches:
      - master

jobs:
  deploy_hasura:
      runs-on: ubuntu-latest
      timeout-minutes: 5

      steps:

      # Checkout
      - name: Checkout code
        uses: actions/checkout@master
        with:
          ref: master

      # Copy Config
      - name: Copy Config
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key : ${{ secrets.SERVER_PRIVATE }}
          source: "hasura"
          target: "deploy"
          rm: false
          
      # Deploy
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key : ${{ secrets.SERVER_PRIVATE }}
          script: |
            cd ./deploy/hasura
            echo POSTGRES_PASSWORD="${{secrets.POSTGRES_PASSWORD}}" > .env
            echo HASURA_GRAPHQL_ADMIN_SECRET="${{secrets.HASURA_GRAPHQL_ADMIN_SECRET}}" >> .env
            echo HASURA_GRAPHQL_ADMIN_SECRET="${{secrets.HASURA_GRAPHQL_ADMIN_SECRET}}" >> .env
            docker-compose up -d -V --no-deps 