name: Deploy Reverse Proxy

on:
  push:
    paths:
      - "reverse_proxy/**"
      - ".github/workflows/reverse_proxy.yml"
    branches:
      - master

jobs:
  deploy_reverse_proxy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

      # Checkout
      - name: Checkout code
        uses: actions/checkout@master
        with:
          ref: master

      # Copy Config
      - name: Copy Config
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key : ${{ secrets.SERVER_PRIVATE }}
          source: "reverse_proxy"
          target: "./deploy"
          rm: false

      # Deploy
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key : ${{ secrets.SERVER_PRIVATE }}
          # -V, --renew-anon-volumes   Recreate anonymous volumes instead of retrieving
          script: |
            cd ./deploy/reverse_proxy
            docker-compose up -d -V --no-deps 